### ISSUE TITLE
Won't install in 10.14

### ISSUE THREAD

**Issue by danfoy** [devondragon/github-omnifocus#4]
Hey devdragon

I'd love to use this script, but it doesn't seem to work in macOS 10.14 Mojave with OmniFocus 3. I would also love to help fix this, but I'm afraid I don't know any Ruby.

On installation, there is an error with `rb-scpt` v1.0.2 - many warnings about things which have been deprecated as far back as macOS 10.8. Deleting `Gemfile.lock` and reinstalling creates a whole bunch of other issues, but if you change just `rb-scpt` to 1.0.3 it does install.

However, there is then another bug when trying to run the script:

```
Traceback (most recent call last):
	7: from bin/githubomnifocus.rb:220:in `<main>'
	6: from bin/githubomnifocus.rb:215:in `main'
	5: from bin/githubomnifocus.rb:131:in `add_github_issues_to_omnifocus'
	4: from bin/githubomnifocus.rb:131:in `each'
	3: from bin/githubomnifocus.rb:152:in `block in add_github_issues_to_omnifocus'
	2: from bin/githubomnifocus.rb:97:in `add_task'
	1: from /Users/danfoy/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:646:in `method_missing'
/Users/danfoy/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:676:in `rescue in method_missing': Unknown property, element or command: 'flattened_contexts' (RuntimeError)
```

I wondered if this was to do with Omni changing from contexts to tags in v3. I'm afraid I know neither Ruby nor OmniFocus's AppleScript API, but a simple find-replace for `context` > `tag` in `githubomnifocus.rb` doesn't solve the issue (although the error message for that does suggest that it's fetching from GitHub properly)

**Comment by devondragon** [comment]
Reproduced locally.

**Comment by devondragon** [comment]
Fixed!
