### ISSUE TITLE
OmniFocus 2 or 3?

### ISSUE THREAD

**Issue by agarrharr** [devondragon/github-omnifocus#6]
Does this work with OmniFocus 3 or just OmniFocus 2? or both? And do you have to have the desktop version of the app installed? Or does it use an OmniFocus API?

**Comment by devondragon** [comment]
Currently 2.  There's some changes I need to make for 3.  It requires the desktop app to be installed, as it uses AppleScript to talk to OF.

**Comment by yesnault** [comment]
@agarrharr see https://github.com/devondragon/github-omnifocus/tree/feature/of-31 for OF3
